name: PyPiPublish

on:
  push:
    branches:
      - master  # Set the branch you want to trigger the workflow on

jobs:
  publish:
    runs-on: ubuntu-latest  # You can specify a different runner if needed

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.x # Use the Python version you require

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build twine
        working-directory: .  # Adjust the directory where your main.py is located

      - name: Build package
        run: python -m build
        working-directory: .  # Adjust the directory where your main.py is located

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__  # PyPI token
          password: ${{ secrets.PYPI_TOKEN }}  # PyPI token
        working-directory: .  # Adjust the directory where your main.py is located

# pypi-AgEIcHlwaS5vcmcCJDQ5NGM3MmZkLTI5NzMtNGM5ZS1iY2JlLTc3MGJmYTkyOTgzMwACKlszLCJiM2Y4M2VkNy03MWIzLTQ1MDYtYWZmNy1lNjg2MTM1MGU5ZjUiXQAABiA1reO6xQ49J2Bn8Mx0kw2PGBFkbxji8CCRXX5mFTMlTg